services:

  db:
    image: postgres:16
    container_name: mimic_pg
    environment:
      POSTGRES_USER:     mimic
      POSTGRES_PASSWORD: mimic
      POSTGRES_DB:       mimiciv
    ports:
      - "5433:5432"
    volumes:
      - mimic_pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c shared_buffers=4GB
      -c maintenance_work_mem=2GB
      -c work_mem=256MB
      -c max_wal_size=16GB
      -c checkpoint_completion_target=0.9
      -c synchronous_commit=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c fsync=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mimic -d mimiciv"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mimic_pgdata:
